language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-es
  
before_script:
  - composer --dev --prefer-source install

script: phpunit
